export const DEFAULT_USERS = [
  {
    id: 'rafael',
    name: 'Rafael',
    role: 'Gestor de OS',
    email: 'rafael@empresa.com',
    status: 'Ativo',
    active: true,
  },
  {
    id: 'leonardo',
    name: 'Leonardo',
    role: 'Diretor',
    email: 'leonardo@empresa.com',
    status: 'Ativo',
    active: true,
  },
  {
    id: 'murilo',
    name: 'Murilo',
    role: 'Diretor',
    email: 'murilo@empresa.com',
    status: 'Ativo',
    active: true,
  },
  {
    id: 'pedro',
    name: 'Pedro',
    role: 'Diretor',
    email: 'pedro@empresa.com',
    status: 'Ativo',
    active: true,
  },
  {
    id: 'fernando',
    name: 'Fernando',
    role: 'Aprovador Contratos',
    email: 'fernando@empresa.com',
    status: 'Ativo',
    active: true,
  },
  {
    id: 'geovana',
    name: 'Geovana',
    role: 'Financeiro',
    email: 'geovana@empresa.com',
    status: 'Ativo',
    active: true,
  },
  {
    id: 'equipe-climatizacao',
    name: 'Equipe Climatizacao',
    role: 'Tecnico (Interno)',
    email: 'clima@empresa.com',
    status: 'Ativo',
    active: true,
  },
  {
    id: 'eletrica-jose',
    name: 'Eletrica Jose',
    role: 'Terceirizado',
    email: 'contato@eletricajose.com.br',
    status: 'Pendente',
    active: true,
  },
];

export const DEFAULT_TEAMS = [
  { id: 'construtora', name: 'Construtora', type: 'internal', active: true },
  { id: 'informatica', name: 'Informatica', type: 'internal', active: true },
  { id: 'infra-compras', name: 'Infra - Compras', type: 'internal', active: true },
  { id: 'infra-coordenacao', name: 'Infra - Coordenacao', type: 'internal', active: true },
  { id: 'infra-sede', name: 'Infra - Sede', type: 'internal', active: true },
  { id: 'jy', name: 'JY', type: 'internal', active: true },
  { id: 'marketing', name: 'Marketing', type: 'internal', active: true },
  { id: 'metalurgica', name: 'Metalurgica', type: 'internal', active: true },
  { id: 'nao-especificado', name: 'Nao especificado', type: 'internal', active: true },
  { id: 'redes', name: 'Redes', type: 'internal', active: true },
  { id: 'refrigeracao', name: 'Refrigeracao', type: 'internal', active: true },
  { id: 'fornecedor-externo', name: 'Fornecedor externo', type: 'external', active: true },
];

export const DEFAULT_VENDORS = [
  { id: 'eletrica-jose', name: 'Eletrica Jose', email: 'contato@eletricajose.com.br', active: true },
  { id: 'decor-interiores', name: 'Decor Interiores', email: '', active: true },
  { id: 'ambientes-cia', name: 'Ambientes & Cia', email: '', active: true },
  { id: 'reforma-facil', name: 'Reforma Facil LTDA', email: '', active: true },
  { id: 'powertech-geradores', name: 'PowerTech Geradores', email: '', active: true },
  { id: 'limpeza-das-alturas', name: 'Limpeza das Alturas Ltda.', email: '', active: true },
  { id: 'serralheria-forte', name: 'Serralheria Forte', email: '', active: true },
];
