import { TICKET_STATUS, type TicketStatus } from './ticketStatus';

export type AppActorRole = 'Admin' | 'Diretor' | 'Usuario';
export type FlowScreen = 'inbox' | 'approvals' | 'finance' | 'tracking';

type TransitionMap = Partial<Record<TicketStatus, TicketStatus[]>>;

const ADMIN_INBOX_TRANSITIONS: TransitionMap = {
  [TICKET_STATUS.NEW]: [TICKET_STATUS.WAITING_TECH_OPINION, TICKET_STATUS.CANCELED],
  [TICKET_STATUS.WAITING_TECH_OPINION]: [TICKET_STATUS.WAITING_SOLUTION_APPROVAL, TICKET_STATUS.CANCELED],
  [TICKET_STATUS.WAITING_SOLUTION_APPROVAL]: [TICKET_STATUS.WAITING_BUDGET, TICKET_STATUS.CANCELED],
  [TICKET_STATUS.WAITING_BUDGET]: [TICKET_STATUS.WAITING_BUDGET_APPROVAL, TICKET_STATUS.CANCELED],
  [TICKET_STATUS.WAITING_BUDGET_APPROVAL]: [TICKET_STATUS.WAITING_CONTRACT_UPLOAD, TICKET_STATUS.CANCELED],
  [TICKET_STATUS.WAITING_CONTRACT_UPLOAD]: [TICKET_STATUS.WAITING_CONTRACT_APPROVAL, TICKET_STATUS.CANCELED],
  [TICKET_STATUS.WAITING_CONTRACT_APPROVAL]: [TICKET_STATUS.WAITING_PRELIM_ACTIONS, TICKET_STATUS.CANCELED],
  [TICKET_STATUS.WAITING_PRELIM_ACTIONS]: [TICKET_STATUS.IN_PROGRESS, TICKET_STATUS.CANCELED],
  [TICKET_STATUS.IN_PROGRESS]: [TICKET_STATUS.WAITING_MAINTENANCE_APPROVAL, TICKET_STATUS.CANCELED],
  [TICKET_STATUS.WAITING_MAINTENANCE_APPROVAL]: [TICKET_STATUS.WAITING_PAYMENT, TICKET_STATUS.IN_PROGRESS, TICKET_STATUS.CANCELED],
  [TICKET_STATUS.WAITING_PAYMENT]: [TICKET_STATUS.CLOSED, TICKET_STATUS.CANCELED],
  [TICKET_STATUS.CLOSED]: [TICKET_STATUS.IN_PROGRESS],
  [TICKET_STATUS.CANCELED]: [TICKET_STATUS.NEW],
};

const DIRECTOR_APPROVAL_TRANSITIONS: TransitionMap = {
  [TICKET_STATUS.WAITING_SOLUTION_APPROVAL]: [TICKET_STATUS.WAITING_BUDGET, TICKET_STATUS.CANCELED],
  [TICKET_STATUS.WAITING_BUDGET_APPROVAL]: [TICKET_STATUS.WAITING_CONTRACT_UPLOAD, TICKET_STATUS.CANCELED],
  [TICKET_STATUS.WAITING_CONTRACT_APPROVAL]: [TICKET_STATUS.WAITING_PRELIM_ACTIONS, TICKET_STATUS.CANCELED],
};

const FINANCE_TRANSITIONS: TransitionMap = {
  [TICKET_STATUS.WAITING_PAYMENT]: [TICKET_STATUS.CLOSED],
};

const TRACKING_TRANSITIONS: TransitionMap = {
  [TICKET_STATUS.WAITING_MAINTENANCE_APPROVAL]: [TICKET_STATUS.WAITING_PAYMENT, TICKET_STATUS.IN_PROGRESS],
  [TICKET_STATUS.WAITING_PAYMENT]: [TICKET_STATUS.WAITING_PAYMENT],
};

const FLOW_TRANSITIONS: Record<AppActorRole, Partial<Record<FlowScreen, TransitionMap>>> = {
  Admin: {
    inbox: ADMIN_INBOX_TRANSITIONS,
    approvals: DIRECTOR_APPROVAL_TRANSITIONS,
    finance: FINANCE_TRANSITIONS,
    tracking: TRACKING_TRANSITIONS,
  },
  Diretor: {
    approvals: DIRECTOR_APPROVAL_TRANSITIONS,
    finance: FINANCE_TRANSITIONS,
    tracking: TRACKING_TRANSITIONS,
  },
  Usuario: {},
};

export function getAllowedNextStatuses(role: AppActorRole, screen: FlowScreen, currentStatus: TicketStatus) {
  const transitions = FLOW_TRANSITIONS[role]?.[screen];
  if (!transitions) return [] as TicketStatus[];
  return transitions[currentStatus] || [];
}

export function canTransitionStatus(
  role: AppActorRole,
  screen: FlowScreen,
  currentStatus: TicketStatus,
  nextStatus: TicketStatus
) {
  if (currentStatus === nextStatus) return true;
  return getAllowedNextStatuses(role, screen, currentStatus).includes(nextStatus);
}

